<?php

namespace Lemaur\Cms\Tests\Feature\Models;

use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Str;
use Lemaur\Cms\Models\Navigation;
use Lemaur\Cms\Models\Page;
use Lemaur\Cms\Tests\Feature\User;
use Lemaur\Cms\Tests\Feature\User as TestUser;
use Lemaur\Cms\Tests\TestCase;
use Lemaur\Cms\Traits\HasExcerpt;
use Lemaur\Cms\Traits\HasMetaDescription;
use Lemaur\Cms\Traits\HasMetaTitle;

class PageTest extends TestCase
{
    /** @test */
    public function it_may_belongs_to_a_user(): void
    {
        $user = TestUser::create(['email' => 'maurizio@example.com']);
        $page = Page::create(['user_id' => $user->id, 'title' => 'My PageRepository']);

        self::assertInstanceOf(BelongsTo::class, $page->user());
        self::assertInstanceOf(TestUser::class, $page->user);

        $page = Page::create(['user_id' => null, 'title' => 'My PageRepository']);

        self::assertEquals(null, $page->user);
    }

    /** @test */
    public function it_may_has_navigations()
    {
        $page = Page::factory()->create();

        $page->navigations()->create(['type' => Navigation::PRIMARY]);

        $this->assertInstanceOf(HasMany::class, $page->navigations());
        $this->assertInstanceOf(Collection::class, $page->navigations);
        $this->assertCount(1, $page->navigations);
        $this->assertDatabaseHas('navigations', [
            'page_id' => $page->id, 'type' => Navigation::PRIMARY,
        ]);

        $page->navigations()->create(['type' => Navigation::SECONDARY]);

        $this->assertCount(2, $page->fresh()->navigations);
        $this->assertDatabaseHas('navigations', [
            'page_id' => $page->id, 'type' => Navigation::SECONDARY,
        ]);
    }

    /** @test */
    public function it_has_autogenerated_slug_from_title(): void
    {
        Page::create(['title' => 'My Page']);

        $this->assertDatabaseHas('pages', ['title' => 'My Page', 'slug' => 'my-page']);
    }

    /** @test */
    public function it_has_unique_slugs()
    {
        Page::create(['title' => 'My Page']);
        Page::create(['title' => 'My Page']);

        $this->assertDatabaseHas('pages', ['slug' => 'my-page']);
        $this->assertDatabaseHas('pages', ['slug' => 'my-page-1']);
    }

    /** @test */
    public function it_has_autogenerated_parent_from_page_model()
    {
        $parent = Page::create(['title' => 'Parent']);
        $page = Page::create(['title' => 'PageRepository', 'parent' => $parent]);

        $this->assertEquals(null, $parent->parent);
        $this->assertEquals('parent', $page->parent);

        $this->assertDatabaseHas('pages', ['parent' => null, 'title' => 'Parent']);
        $this->assertDatabaseHas('pages', ['parent' => 'parent', 'title' => 'PageRepository']);
    }

    /** @test */
    public function it_has_autogenerated_parent_from_nested_page_model()
    {
        $parent = Page::create(['title' => 'Parent']);
        $child = Page::create(['title' => 'Child', 'parent' => $parent]);
        $page = Page::create(['title' => 'PageRepository', 'parent' => $child]);

        $this->assertEquals(null, $parent->parent);
        $this->assertEquals('parent', $child->parent);
        $this->assertEquals('parent/child', $page->parent);

        $this->assertDatabaseHas('pages', ['parent' => null, 'title' => 'Parent']);
        $this->assertDatabaseHas('pages', ['parent' => 'parent', 'title' => 'Child']);
        $this->assertDatabaseHas('pages', ['parent' => 'parent/child', 'title' => 'PageRepository']);
    }

    /** @test */
    public function it_has_autogenerated_parent_from_deeply_nested_page_model()
    {
        $first = Page::create(['title' => 'First']);
        $second = Page::create(['title' => 'Second', 'parent' => $first]);
        $third = Page::create(['title' => 'Third', 'parent' => $second]);
        $fourth = Page::create(['title' => 'Fourth', 'parent' => $third]);

        $this->assertEquals(null, $first->parent);
        $this->assertEquals('first', $second->parent);
        $this->assertEquals('first/second', $third->parent);
        $this->assertEquals('first/second/third', $fourth->parent);

        $this->assertDatabaseHas('pages', ['parent' => null, 'title' => 'First']);
        $this->assertDatabaseHas('pages', ['parent' => 'first', 'title' => 'Second']);
        $this->assertDatabaseHas('pages', ['parent' => 'first/second', 'title' => 'Third']);
        $this->assertDatabaseHas('pages', ['parent' => 'first/second/third', 'title' => 'Fourth']);
    }

    /** @test */
    public function it_has_autogenerated_parent_from_page_slug()
    {
        $parent = Page::create(['title' => 'Parent']);
        $page = Page::create(['title' => 'PageRepository', 'parent' => $parent->slug]);

        $this->assertEquals(null, $parent->parent);
        $this->assertEquals('parent', $page->parent);

        $this->assertDatabaseHas('pages', ['parent' => null, 'title' => 'Parent']);
        $this->assertDatabaseHas('pages', ['parent' => 'parent', 'title' => 'PageRepository']);
    }

    /** @test */
    public function it_has_autogenerated_parent_from_nested_page_slug()
    {
        $parent = Page::create(['title' => 'Parent']);
        $child = Page::create(['title' => 'Child', 'parent' => $parent->slug]);
        $page = Page::create(['title' => 'PageRepository', 'parent' => $child->slug]);

        $this->assertEquals(null, $parent->parent);
        $this->assertEquals('parent', $child->parent);
        $this->assertEquals('parent/child', $page->parent);

        $this->assertDatabaseHas('pages', ['parent' => null, 'title' => 'Parent']);
        $this->assertDatabaseHas('pages', ['parent' => 'parent', 'title' => 'Child']);
        $this->assertDatabaseHas('pages', ['parent' => 'parent/child', 'title' => 'PageRepository']);
    }

    /** @test */
    public function it_has_autogenerated_parent_from_deeply_nested_page_slug()
    {
        $first = Page::create(['title' => 'First']);
        $second = Page::create(['title' => 'Second', 'parent' => $first->slug]);
        $third = Page::create(['title' => 'Third', 'parent' => $second->slug]);
        $fourth = Page::create(['title' => 'Fourth', 'parent' => $third->slug]);

        $this->assertEquals(null, $first->parent);
        $this->assertEquals('first', $second->parent);
        $this->assertEquals('first/second', $third->parent);
        $this->assertEquals('first/second/third', $fourth->parent);

        $this->assertDatabaseHas('pages', ['parent' => null, 'title' => 'First']);
        $this->assertDatabaseHas('pages', ['parent' => 'first', 'title' => 'Second']);
        $this->assertDatabaseHas('pages', ['parent' => 'first/second', 'title' => 'Third']);
        $this->assertDatabaseHas('pages', ['parent' => 'first/second/third', 'title' => 'Fourth']);
    }

    /** @test */
    public function it_may_has_extra_attributes()
    {
        $page = Page::factory()->create();

        // Set extra attribute
        $page->setExtraAttribute('meta', [
            'title' => 'Meta Title',
            'description' => 'Meta Description',
        ]);

        // Get extra attributes
        $this->assertEquals([
            'title' => 'Meta Title',
            'description' => 'Meta Description',
        ], $page->getExtraAttribute('meta'));

        // Has extra attribute
        $this->assertTrue($page->hasExtraAttribute('meta'));

        // Forget extra attribute
        $page->forgetExtraAttribute('meta');

        $this->assertFalse($page->hasExtraAttribute('meta'));

        // Fill extra attributes
        $page->fillExtraAttributes([
            'meta' => [
                'title' => 'Meta Title',
                'description' => 'Meta Description',
            ],
        ]);

        $this->assertEquals([
            'title' => 'Meta Title',
            'description' => 'Meta Description',
        ], $page->getExtraAttribute('meta'));
    }

    /** @test */
    public function it_may_has_excerpt()
    {
        $content = Page::factory()->raw(['excerpt' => 'excerpt']);

        $page = TestPage::create($content);

        $this->assertEquals('excerpt', $page->fresh()->excerpt);
    }

    /** @test */
    public function it_may_has_layout()
    {
        $content = Page::factory()->raw(['layout' => 'basic']);

        $page = TestPage::create($content);

        $this->assertEquals('basic', $page->fresh()->layout);
    }

    /** @test */
    public function it_may_has_meta_title()
    {
        $content = Page::factory()->raw(['meta_title' => 'meta title']);

        $page = TestPage::create($content);

        $this->assertEquals('meta title', $page->fresh()->meta_title);
    }

    /** @test */
    public function it_may_has_meta_title_autogenerated_by_page_title()
    {
        $content = Page::factory()->raw(['title' => 'My Title']);

        $page = TestPage::create($content);

        $this->assertEquals('My Title', $page->meta_title);
    }

    /** @test */
    public function it_may_has_meta_description()
    {
        $content = Page::factory()->raw(['meta_description' => 'meta description']);

        $page = TestPage::create($content);

        $this->assertEquals('meta description', $page->fresh()->meta_description);
    }

    /** @test */
    public function it_may_has_meta_description_autogenerated_by_page_content()
    {
        $content = Page::factory()->raw();

        $page = TestPage::create($content);

        $this->assertNotNull($page->meta_description);
        $this->assertTrue(Str::length($page->meta_description) <= Page::META_DESCRIPTION_LIMIT);
    }

    /** @test */
    public function it_returns_the_available_parents_page()
    {
        $parents = Page::factory()->count(3)->create();
        $child = Page::factory()->create(['parent' => $parents->first()->slug]);

        $this->assertIsArray(Page::getAvailableParents());
        $this->assertCount(3, Page::getAvailableParents());
        $this->assertArrayNotHasKey($child->slug, Page::getAvailableParents());
    }

    /** @test */
    public function it_returns_the_available_layouts()
    {
        Page::factory()->create(['layout' => 'service']);
        Page::factory()->create(['layout' => 'blog']);
        Page::factory()->count(5)->create(['layout' => 'basic']);
        Page::factory()->create();

        $this->assertIsArray(Page::getAvailableLayouts());
        $this->assertCount(3, Page::getAvailableLayouts());
    }

    /** @test */
    public function it_belogs_to_its_author()
    {
        $user = User::create(['email' => 'john.doe@example.com']);

        $this->actingAs($user);

        $content = Page::factory()->raw();

        $page = Page::create($content);

        $this->assertEquals($user->id, $page->user->id);
    }

    /** @test */
    public function it_may_has_media_collections()
    {
        $page = Page::factory()->create();

        $image = UploadedFile::fake()->image('image.png');
        $page->addMedia($image)->toMediaCollection('page.image.collection');

        $this->assertSame($image->name, $page->getMedia('page.image.collection')->first()->file_name);
    }

    /** @test */
    public function it_may_has_type()
    {
        $page1 = Page::factory()->create();
        $page2 = Page::factory()->create(['type' => 'article']);

        $article = Page::withType(null)->first();
        $this->assertEquals($page1->id, $article->id);

        $article = Page::withType('article')->first();
        $this->assertEquals($page2->id, $article->id);
    }

    /** @test */
    public function it_generates_full_slug()
    {
        $first = Page::create(['title' => 'First']);
        $second = Page::create(['title' => 'Second', 'parent' => $first->slug]);
        $third = Page::create(['title' => 'Third', 'parent' => $second->slug]);
        $fourth = Page::create(['title' => 'Fourth', 'parent' => $third->slug]);

        $this->assertEquals('/first', $first->full_slug);
        $this->assertEquals('/first/second', $second->full_slug);
        $this->assertEquals('/first/second/third', $third->full_slug);
        $this->assertEquals('/first/second/third/fourth', $fourth->full_slug);
    }
}

class TestPage extends Page
{
    use HasExcerpt;
    use HasMetaTitle;
    use HasMetaDescription;
}
