name: run-tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.0, 8.1]
        laravel: [8.*, 9.*]
        stability: [prefer-stable]
        exclude:
          - php: 8.0
            laravel: 9.*
        include:
          - laravel: 8.*
            testbench: ^6.6
            markdown: ^0.2
            seotools: ^v0.20
            publishing: ^1.0
            medialibrary: ^9.0
          - laravel: 9.*
            testbench: 7.*
            markdown: ^0.3
            seotools: ^v0.22
            publishing: ^2.0
            medialibrary: ^10.0.3

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "illuminate/contracts:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "lemaur/markdown:${{ matrix.markdown }}" "artesaos/seotools:${{ matrix.seotools }}" "lemaur/eloquent-publishing:${{ matrix.publishing }}" "spatie/laravel-medialibrary:${{ matrix.medialibrary }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit
